[project]
name = "myproject"
requires-python = ">=3.11"
dynamic=["version"]
dependencies=["pre-commit","flexget"]

[tool.hatch.version]
path = "myproject/version.py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
